update CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -55,8 +55,14 @@ jobs:
     - uses: cachix/install-nix-action@v20
       with:
         nix_path: nixpkgs=channel:nixos-${{ env.NIXOS_VERSION }}
-    - run: >
-        [[ -z $(python scripts/check_deps.py) ]]
+    - run: |
+        num_side_branches=$(python scripts/check_deps.py | wc -l)
+        if [[ $num_side_branches -ge 0 ]]; then
+          echo "ERROR: Detected $num_side_branches dependencies on a side branch"
+          exit 1
+        else
+          echo "No dependencies detected on a side branch"
+        fi
   envs:
     name: Build Environments
     runs-on: ubuntu-latest
