Add user cloud sync jobs via orchestrator on all machines (#229)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,6 +47,22 @@ jobs:
         nix_path: nixpkgs=channel:nixos-${{ env.NIXOS_VERSION }}
     - run: >
         nix flake lock --no-update-lock-file
+  check-deps:
+    name: Check Dependencies
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - uses: cachix/install-nix-action@v20
+      with:
+        nix_path: nixpkgs=channel:nixos-${{ env.NIXOS_VERSION }}
+    - run: |
+        num_side_branches=$(python scripts/check_deps.py | wc -l)
+        if [[ $num_side_branches -ge 1 ]]; then
+          echo "ERROR: Detected $num_side_branches dependencies on a side branch"
+          exit 1
+        else
+          echo "No dependencies detected on a side branch"
+        fi
   envs:
     name: Build Environments
     runs-on: ubuntu-latest
